#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "calcom"
name = "cal.com"
description.en = "Appointment scheduling application"
description.fr = "Application de planification de rendez-vous"

version = "4.3.3~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://cal.com/"
code = "https://github.com/calcom"

[integration]
yunohost = ">= 11.2.14"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "12G"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/calcom/cal.com/archive/refs/tags/v4.3.6.tar.gz"
    sha256 = "f28ccf0831a21d125ce6501322eb8ceaae83a55cff96a43565fb995d3da0062f"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"
